### ISSUE TITLE
Usage link broken

### ISSUE THREAD

**Issue by colindaven** [snakemake-workflows/dna-seq-varlociraptor#102]
Hi,

this link no longer leads to usage:

https://snakemake.github.io/snakemake-workflow-catalog/?usage=snakemake-workflows%2Fdna-seq-varlociraptorhttps://snakemake.github.io/snakemake-workflow-catalog/?usage=snakemake-workflows%2Fdna-seq-varlociraptor

Thanks

**Comment by FelixMoelder** [comment]
Thank you for reporting.
It looks like the error is caused in the [snakemake-worlflow-catalog repository](https://github.com/snakemake/snakemake-workflow-catalog).
@johanneskoester May you have a look at this? It seems like the github-action removed all content during its latest commit (https://github.com/snakemake/snakemake-workflow-catalog/commit/a32a692689282768d70f9227a5d5fb1b93cf1b79)

**Comment by colindaven** [comment]
Works again, thanks!
