### ISSUE TITLE
estimate TMB in tumor only variants

### ISSUE THREAD

**Issue by yihancc** [snakemake-workflows/dna-seq-varlociraptor#131]
Hi! Thanks for this wonderful tool!

I used varlociraptor for tumor only variant calling, and now I want to use its "estimate mutational-burden" funtion to estimate the TMB in my data. I tried this code`varlociraptor estimate mutational-burden --coding-genome-size 6.5e3 --events SOMATIC_TUMOR+GERMILNE_TUMOR --plot-mode curve --sample calls_anno.vcf`, but I got nothing even the error message.

Can I use "estimate mutational-burden" to estimate TMB in the tumor only variants? If so, is there anything wrong with my usage?

Thank you for your time!

**Comment by johanneskoester** [comment]
Multiple events have to be specified whitespace separated, not by "+", i.e.
```bash
varlociraptor estimate mutational-burden --coding-genome-size 6.5e3 --events SOMATIC_TUMOR GERMILNE_TUMOR --plot-mode curve --sample calls_anno.vcf
```
