### ISSUE TITLE
issues with cutadapt

### ISSUE THREAD

**Issue by piecrivello** [snakemake-workflows/dna-seq-varlociraptor#155]
Hi everyone,

I am having trouble using this pipeline apparently at the step of cutadapt.

For my analysis I submitted already trimmed fastq files, and so I left empty the adapters field in units.tsv and I deactivated trimming in the config.yaml.

By running the pipeline, I got errors from the rules cutadapt-pe and cutadapt-pipe with no information in their corresponding log files. The only informative massage seems to be in the terminal as the following:

```
Traceback (most recent call last):
  File "/mnt/data/crivellopi/Bioinformatics/dna-seq-varlociraptor/.snakemake/scripts/tmpgsy5av3k.wrapper.py", line 23, in <module>
    assert (
AssertionError: No options provided to cutadapt. Please use 'params: adapters=' or 'params: extra='.
```

I hope you can help me solving this.

All the best,
Pietro

**Comment by Austin-s-h** [comment]
https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth/pull/67 Should also be applicable wherever cutadapt is used

**Comment by johanneskoester** [comment]
This should be solved since a while, sorry for the glitch.
